apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  podSelector:
    matchLabels:
      role: 
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 
        except:
        - 
    - namespaceSelector:
        matchLabels:
          project: 
    - podSelector:
        matchLabels:
          role: 
    ports:
    - protocol: TCP
      port: {{ .Port }}
  egress:
  - to:
    - ipBlock:
        cidr: 
    ports:
    - protocol: TCP
      port: 