apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  podSelector:
    matchLabels:
      role: {{ .SpecMatchLabelRole }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .IngressCidr }}
        except: 
        - {{ .IngressIpBlockExcept }}
    - namespaceSelector:
        matchLabels:
          project: {{ .IngressNamespaceMatchLabel }}
    - podSelector:
        matchLabels:
          role: {{ .IngressPodSelectorMatchLabel }}
    ports:
    - protocol: TCP
      port: {{ .IngressPort }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .EgressCidr }}
    ports:
    - protocol: TCP
      port: {{ .EgressPort }}